// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV2YRSrwV5dNweFaIijvRuAVt3Y7UcbSc',
    appId: '1:965551358547:web:9c110760dfada079d13ca6',
    messagingSenderId: '965551358547',
    projectId: 'cw06-9b7c8',
    authDomain: 'cw06-9b7c8.firebaseapp.com',
    storageBucket: 'cw06-9b7c8.firebasestorage.app',
    measurementId: 'G-FT7R4J0D32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhdJiXTEP7Ttgm8KfO-dto1__DuKruv8A',
    appId: '1:965551358547:android:6ceb25db6a3633c2d13ca6',
    messagingSenderId: '965551358547',
    projectId: 'cw06-9b7c8',
    storageBucket: 'cw06-9b7c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXw_imfwGzJuuCW1wCaU2NCmKHk7RSkqI',
    appId: '1:965551358547:ios:9b807f8b16e93c94d13ca6',
    messagingSenderId: '965551358547',
    projectId: 'cw06-9b7c8',
    storageBucket: 'cw06-9b7c8.firebasestorage.app',
    iosBundleId: 'com.example.cw6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXw_imfwGzJuuCW1wCaU2NCmKHk7RSkqI',
    appId: '1:965551358547:ios:9b807f8b16e93c94d13ca6',
    messagingSenderId: '965551358547',
    projectId: 'cw06-9b7c8',
    storageBucket: 'cw06-9b7c8.firebasestorage.app',
    iosBundleId: 'com.example.cw6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV2YRSrwV5dNweFaIijvRuAVt3Y7UcbSc',
    appId: '1:965551358547:web:396a9c81c77cf79dd13ca6',
    messagingSenderId: '965551358547',
    projectId: 'cw06-9b7c8',
    authDomain: 'cw06-9b7c8.firebaseapp.com',
    storageBucket: 'cw06-9b7c8.firebasestorage.app',
    measurementId: 'G-2JRMZL3YBQ',
  );
}
